#!/bin/bash
#
# Setup script to add sudo permissions for nordmacpy VPN package
# This script adds passwordless sudo access for the commands required by the VPN package
#
# Usage: ./setup_sudo_permissions.sh
# Note: This script must be run with sudo privileges

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}Error: This script must be run as root (use sudo)${NC}" >&2
   exit 1
fi

# Get the current user (the one who invoked sudo)
CURRENT_USER="${SUDO_USER:-${USER}}"
if [[ -z "$CURRENT_USER" ]] || [[ "$CURRENT_USER" == "root" ]]; then
    echo -e "${RED}Error: Could not determine the current user. Please run: sudo -u \$USER $0${NC}" >&2
    exit 1
fi

echo -e "${GREEN}Setting up sudo permissions for user: $CURRENT_USER${NC}"

# Find openvpn binary location
OPENVPN_PATH=$(command -v openvpn 2>/dev/null || echo "")
if [[ -z "$OPENVPN_PATH" ]]; then
    echo -e "${YELLOW}Warning: openvpn not found in PATH.${NC}"
    echo -e "${YELLOW}Checking common installation locations...${NC}"
    
    # Check common locations
    POSSIBLE_PATHS=(
        "/usr/local/bin/openvpn"
        "/opt/homebrew/bin/openvpn"
        "/usr/bin/openvpn"
        "/opt/local/bin/openvpn"
    )
    
    FOUND_PATHS=()
    for path in "${POSSIBLE_PATHS[@]}"; do
        if [[ -f "$path" ]]; then
            FOUND_PATHS+=("$path")
        fi
    done
    
    if [[ ${#FOUND_PATHS[@]} -eq 0 ]]; then
        echo -e "${RED}Error: openvpn not found. Please install it first:${NC}"
        echo -e "${YELLOW}  brew install openvpn${NC}"
        exit 1
    else
        OPENVPN_PATH="${FOUND_PATHS[0]}"
        echo -e "${GREEN}Found openvpn at: $OPENVPN_PATH${NC}"
        if [[ ${#FOUND_PATHS[@]} -gt 1 ]]; then
            echo -e "${YELLOW}Note: Multiple openvpn installations found. Using: $OPENVPN_PATH${NC}"
        fi
    fi
else
    echo -e "${GREEN}Found openvpn at: $OPENVPN_PATH${NC}"
fi

# Create sudoers.d directory if it doesn't exist
SUDOERS_D="/etc/sudoers.d"
mkdir -p "$SUDOERS_D"

# Create the sudoers file
SUDOERS_FILE="$SUDOERS_D/nordmacpy-$CURRENT_USER"
TEMP_FILE=$(mktemp)

cat > "$TEMP_FILE" <<EOF
# Sudo permissions for nordmacpy VPN package
# User: $CURRENT_USER
# Generated by setup_sudo_permissions.sh
# DO NOT EDIT MANUALLY - regenerate using the setup script

# OpenVPN - allow all openvpn commands (needed because args vary)
$CURRENT_USER ALL=(ALL) NOPASSWD: $OPENVPN_PATH

# Route commands for cleanup
$CURRENT_USER ALL=(ALL) NOPASSWD: /sbin/route -n delete -inet 0.0.0.0/1
$CURRENT_USER ALL=(ALL) NOPASSWD: /sbin/route -n delete -inet 128.0.0.0/1

# DNS cache flush
$CURRENT_USER ALL=(ALL) NOPASSWD: /usr/bin/dscacheutil -flushcache

# mDNSResponder restart
$CURRENT_USER ALL=(ALL) NOPASSWD: /usr/bin/killall -HUP mDNSResponder

# OpenVPN process management
$CURRENT_USER ALL=(ALL) NOPASSWD: /usr/bin/pkill -TERM openvpn
$CURRENT_USER ALL=(ALL) NOPASSWD: /usr/bin/pkill -KILL openvpn
EOF

# Validate the sudoers file syntax
echo -e "${GREEN}Validating sudoers syntax...${NC}"
if visudo -c -f "$TEMP_FILE" 2>/dev/null; then
    echo -e "${GREEN}Syntax validation passed${NC}"
else
    echo -e "${RED}Error: Invalid sudoers syntax! Aborting.${NC}" >&2
    rm -f "$TEMP_FILE"
    exit 1
fi

# Check if file already exists
if [[ -f "$SUDOERS_FILE" ]]; then
    echo -e "${YELLOW}Warning: $SUDOERS_FILE already exists${NC}"
    read -p "Overwrite? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo -e "${YELLOW}Aborted. No changes made.${NC}"
        rm -f "$TEMP_FILE"
        exit 0
    fi
    # Backup existing file
    cp "$SUDOERS_FILE" "${SUDOERS_FILE}.backup.$(date +%Y%m%d_%H%M%S)"
    echo -e "${GREEN}Backed up existing file${NC}"
fi

# Install the sudoers file
cp "$TEMP_FILE" "$SUDOERS_FILE"
chmod 0440 "$SUDOERS_FILE"
rm -f "$TEMP_FILE"

echo -e "${GREEN}✓ Sudo permissions installed successfully!${NC}"
echo -e "${GREEN}✓ File location: $SUDOERS_FILE${NC}"
echo ""
echo -e "${YELLOW}Note: You may need to log out and back in for changes to take effect,${NC}"
echo -e "${YELLOW}      or run: sudo -k${NC}"
echo ""
echo -e "${GREEN}To verify, test with: sudo -n openvpn --version${NC}"

